'use client';

import type { ScanResult } from '@/lib/types';
import VerdictBadge from './VerdictBadge';
import ScoreMeter from './ScoreMeter';
import { FindingsSection, RiskFactorsList, LinksList, MetaInfo } from './FindingsSection';
import { useState } from 'react';

interface ScanResultProps {
    result: ScanResult;
    onNewScan: () => void;
}

export default function ScanResultComponent({ result, onNewScan }: ScanResultProps) {
    const [copied, setCopied] = useState(false);
    const { verdict, score, summary, findings, url, durationMs, scannedAt } = result;

    const copyReport = async () => {
        const report = `
Link Checker Report
==================
URL: ${url}
Scanned: ${new Date(scannedAt).toLocaleString()}
Duration: ${durationMs}ms

Verdict: ${verdict.toUpperCase()}
Safety Score: ${score}/100

Summary:
${summary}

Risk Factors:
${findings.riskFactors.length > 0
                ? findings.riskFactors.map(r => `- [${r.severity.toUpperCase()}] ${r.category}: ${r.description}`).join('\n')
                : '- No significant risks detected'}

Links Found: ${findings.totalLinks} (${findings.externalLinks} external, ${findings.suspiciousLinks} suspicious)
Hidden Elements: ${findings.hiddenIframes} iframes, ${findings.hiddenForms} forms
Obfuscated Scripts: ${findings.obfuscatedScripts}

---
Generated by Link Checker
    `.trim();

        try {
            await navigator.clipboard.writeText(report);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch {
            console.error('Failed to copy report');
        }
    };

    return (
        <div className="animate-slide-up">
            {/* Header with verdict */}
            <div className="glass-card p-8 mb-6">
                <div className="flex flex-col lg:flex-row items-center gap-8">
                    {/* Score meter */}
                    <ScoreMeter score={score} verdict={verdict} />

                    {/* Info section */}
                    <div className="flex-1 text-center lg:text-left">
                        <div className="mb-4">
                            <VerdictBadge verdict={verdict} size="lg" />
                        </div>

                        <h2 className="text-sm font-mono text-[var(--muted)] mb-2 break-all">
                            {findings.finalUrl}
                        </h2>

                        <p className="text-lg text-[var(--foreground)] mb-4">
                            {summary}
                        </p>

                        <div className="flex flex-wrap items-center justify-center lg:justify-start gap-4 text-sm text-[var(--muted)]">
                            <span>
                                Scanned in {durationMs}ms
                            </span>
                            <span>•</span>
                            <span>
                                {new Date(scannedAt).toLocaleTimeString()}
                            </span>
                        </div>
                    </div>
                </div>

                {/* Actions */}
                <div className="flex flex-wrap gap-3 mt-6 pt-6 border-t border-[var(--border)]">
                    <button onClick={onNewScan} className="btn-primary">
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M21 12a9 9 0 11-9-9c2.52 0 4.93 1 6.74 2.74L21 8" />
                            <path d="M21 3v5h-5" />
                        </svg>
                        Scan Another URL
                    </button>
                    <button onClick={copyReport} className="btn-secondary">
                        {copied ? (
                            <>
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                    <path d="M20 6L9 17l-5-5" />
                                </svg>
                                Copied!
                            </>
                        ) : (
                            <>
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                                </svg>
                                Copy Report
                            </>
                        )}
                    </button>
                </div>
            </div>

            {/* Detailed findings */}
            <div className="space-y-3">
                {/* Risk Factors */}
                <FindingsSection
                    title="Risk Factors"
                    icon={
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M12 9v4M12 17h.01" />
                            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
                        </svg>
                    }
                    defaultOpen={verdict !== 'safe'}
                    count={findings.riskFactors.length}
                >
                    <RiskFactorsList riskFactors={findings.riskFactors} />
                </FindingsSection>

                {/* Page Information */}
                <FindingsSection
                    title="Page Information"
                    icon={
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <circle cx="12" cy="12" r="10" />
                            <path d="M12 16v-4M12 8h.01" />
                        </svg>
                    }
                    defaultOpen={true}
                >
                    <MetaInfo
                        title={findings.title}
                        description={findings.description}
                        hasOpenGraph={findings.hasOpenGraph}
                        hasTwitterCard={findings.hasTwitterCard}
                        isHttps={findings.isHttps}
                    />
                </FindingsSection>

                {/* Outbound Links */}
                <FindingsSection
                    title="Outbound Links"
                    icon={
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
                            <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
                        </svg>
                    }
                    count={findings.totalLinks}
                >
                    <div className="mb-3 flex flex-wrap gap-2 text-xs">
                        <span className="bg-white/10 px-2 py-1 rounded">
                            {findings.totalLinks} total
                        </span>
                        <span className="bg-white/10 px-2 py-1 rounded">
                            {findings.externalLinks} external
                        </span>
                        {findings.suspiciousLinks > 0 && (
                            <span className="bg-[var(--risk-bg)] text-[var(--risk)] px-2 py-1 rounded">
                                {findings.suspiciousLinks} suspicious
                            </span>
                        )}
                    </div>
                    <LinksList links={findings.outboundLinks} />
                </FindingsSection>

                {/* Hidden Elements */}
                {(findings.hiddenIframes > 0 || findings.hiddenForms > 0 || findings.obfuscatedScripts > 0) && (
                    <FindingsSection
                        title="Hidden Elements"
                        icon={
                            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94" />
                                <path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19" />
                                <path d="M1 1l22 22" />
                            </svg>
                        }
                        defaultOpen={true}
                    >
                        <div className="space-y-2">
                            {findings.hiddenIframes > 0 && (
                                <div className="flex items-center gap-2 p-3 bg-[var(--risk-bg)] rounded-lg">
                                    <span className="text-[var(--risk)]">⚠️</span>
                                    <span className="text-sm">{findings.hiddenIframes} hidden iframe(s) detected</span>
                                </div>
                            )}
                            {findings.hiddenForms > 0 && (
                                <div className="flex items-center gap-2 p-3 bg-[var(--caution-bg)] rounded-lg">
                                    <span className="text-[var(--caution)]">⚠️</span>
                                    <span className="text-sm">{findings.hiddenForms} hidden form(s) detected</span>
                                </div>
                            )}
                            {findings.obfuscatedScripts > 0 && (
                                <div className="flex items-center gap-2 p-3 bg-[var(--caution-bg)] rounded-lg">
                                    <span className="text-[var(--caution)]">⚠️</span>
                                    <span className="text-sm">{findings.obfuscatedScripts} obfuscated script(s) detected</span>
                                </div>
                            )}
                        </div>
                    </FindingsSection>
                )}
            </div>

            {/* Disclaimer */}
            <div className="mt-8 p-4 bg-black/20 rounded-lg border border-[var(--border)]">
                <p className="text-xs text-[var(--muted)] text-center">
                    <strong>Disclaimer:</strong> This analysis is informational only and does not guarantee the safety of any URL.
                    Always exercise caution when visiting unfamiliar websites.
                </p>
            </div>
        </div>
    );
}
